version: '3.5'
services:

  traefik:
    image: "traefik:v2.8.4"
    container_name: traefik
    hostname: traefik
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --api
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.le.acme.email=
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=le"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users="
    restart: unless-stopped

  front:
    image: front:latest
    depends_on:
      - tsignal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.front.rule=Host(`tsignal.store`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=le"
      - "traefik.http.routers.front.service=front"
      - "traefik.http.services.front.loadbalancer.server.port=5173"

  tsignal:
    image: truesignal:latest
    command: bash run.sh
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.tsignal.rule=Host(`api.tsignal.store`)"
      - "traefik.http.routers.tsignal.entrypoints=websecure"
      - "traefik.http.routers.tsignal.tls=true"
      - "traefik.http.routers.tsignal.tls.certresolver=le"
      - "traefik.http.routers.tsignal.service=tsignal"
      - "traefik.http.services.tsignal.loadbalancer.server.port=5656"
    depends_on:
      - vault
      - db


  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tsignal
    ports:
      - '5432:5432'
    volumes:
      - mydata:/var/lib/postgresql/data

  consul:
    image: consul:latest
    volumes:
      - consul-data:/consul/data
    networks:
      - proxy
    command: agent -server -bootstrap-expect=1 -client=consul

  vault:
    image: vault:latest
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_API_ADDR=http://vault:8200
    volumes:
      - vault-data:/vault/data
    networks:
      - proxy
    command: server -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=myroot -dev-plugin-dir=/vault/plugins -config=/vault/config/vault.hcl

volumes:
  consul-data:
  vault-data:

networks:
  default:
    external: true
    name: proxy