version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tsignal
    ports:
      - '5432:5432'
    
  vault:
    image: vault:1.5.2
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    ports:
      - "8200:8200"

  tsignal:
    image: tsignal:latest
    ports:
      - "80:80"
    command: bash ./app/app.py
    depends_on:
      - vault

  


   