app:
  name: TSIGNAL
  host: 0.0.0.0
  port: 5656
  debug: False

environment:
  is_production: False
  
database:
  host: db
  port: 5432
  name: my_database
  user: 9l3oldindimakdaba
  password: ohadapassword9l3ohtahoa
logging:
  level: info
  filename: myapp.log

jwt:
  secret: tsignal_secret_key
  expiration: 5
