app:
  name: TSIGNAL
  host: 0.0.0.0
  port: 5656
  debug: True
  
environment:
  is_production: False
  
database:
  host: db
  port: 5432
  name: tsignal
  user: postgres
  password: postgres
logging:
  level: info
  filename: app.log

jwt:
  secret: MYSECRET
  expiration: 12000
