app:
  name: TSIGNAL
  host: localhost
  port: 5666
  debug: True
  
environment:
  is_production: False
  
database:
  host: localhost
  port: 5432
  name: my_database
  user: my_user
  password: my_password
logging:
  level: info
  filename: myapp.log

jwt:
  secret: MYSECRET
  expiration: 12000
